### ISSUE TITLE
无法使用求助

### ISSUE THREAD

**Issue by Johnluckygogogo** [WXjzcccc/PanelForensics#4]
感谢大神开发这个软件，我将服务器镜像仿真并用SSH连接后，用这个软件无法读取面板信息，服务器镜像是宝塔面板的，检查了环境依赖没发现啥问题，大神帮我看下是什么问题，谢谢。大神有空的时候是否能出一个软件使用的简单教程，再次感谢。镜像地址如下：
链接：https://pan.quark.cn/s/f4e655d0ba01
提取码：rLC2

**Comment by WXjzcccc** [comment]
请使用百度网盘上传

**Comment by Johnluckygogogo** [comment]
> 请使用百度网盘上传
通过网盘分享的文件：server.E01
链接: https://pan.baidu.com/s/17e0cQCAzw18tY76Lt5UvPg?pwd=6666 提取码: 6666 
--来自百度网盘超级会员v6的分享

**Comment by WXjzcccc** [comment]
已修复，请拉取最新仓库后使用

**Comment by Johnluckygogogo** [comment]
> 已修复，请拉取最新仓库后使用

好的，谢谢，我试试看

**Comment by Johnluckygogogo** [comment]
> 已修复，请拉取最新仓库后使用

可以用了，感谢大神的修复！
